name: DEMO deploy
on:
  push:
    branches: ['gh-demo']
    paths: ['./**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Pnpm Install
        working-directory: .
        run: |
          pnpm install
      - name: DEV Build
        working-directory: .
        run: |
          pnpm build:demo
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          # https://github.com/Zettablock/zetta-webcode/settings/secrets/actions
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME_DEMO }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: './.next'
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID_DEMO }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
