name: DEV deploy
on:
  push:
    branches: ['gh-dev']
    paths: ['./**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Pnpm Install
        working-directory: .
        run: |
          pnpm install
      - name: DEV Build
        working-directory: .
        env:
          AI_API_KEY: ${{ vars.DEV_AI_API_KEY }}
          AUTH_CLIENT_ID: ${{ vars.DEV_AUTH_CLIENT_ID }}
          KV_REST_API_URL: ${{ vars.DEV_KV_REST_API_URL }}
          KV_REST_API_TOKEN: ${{ vars.DEV_KV_REST_API_TOKEN }}
          NEXT_PUBLIC_SEGMENT_WRITE_KEY: ${{ vars.DEV_SEGMENT_WRITE_KEY }}
        run: |
          pnpm export:dev
          mkdir -p ./build/aiweb
          mv ./out ./build/aiweb
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          # https://github.com/Zettablock/zetta-webcode/settings/variables/actions
          AWS_S3_BUCKET: ${{ vars.AWS_BUCKET_NAME_DEV }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: './build'
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ vars.AWS_DISTRIBUTION_ID_DEV }}
          PATHS: '/*'
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
